<?php

require 'library.php';

$results =  pull_popular_picks();
echo $results;

echo "\n";
echo 'test2' . "\n";
echo "\n";

$results = pull_results();
echo $results;

?>

!AK#ROMNEY!AL#ROMNEY!AR#ROMNEY!AZ#SANTORUM!CA#ROMNEY!CO#ROMNEY!CT#ROMNEY!DC#DONEGAN!DE#ROMNEY!FL#GINGRICH!GA#ROMNEY!HI#ROMNEY!IA#SANTORUM!ID#ROMNEY!IL#ROMNEY!IN#ROMNEY!KS#ROMNEY!KY#ROMNEY!LA#ROMNEY!MA#ROMNEY!MD#ROMNEY!ME#ROMNEY!MI#ROMNEY!MN#ROMNEY!MO#ROMNEY!MS#ROMNEY!MT#ROMNEY!NC#GINGRICH!ND#ROMNEY!NE#ROMNEY!NH#ROMNEY!NJ#ROMNEY!NM#ROMNEY!NV#ROMNEY!NY#ROMNEY!OH#SANTORUM!OK#ROMNEY!OR#ROMNEY!PA#ROMNEY!RI#ROMNEY!SC#GINGRICH!SD#ROMNEY!TN#SANTORUM!TX#ROMNEY!UT#ROMNEY!VA#ROMNEY!VT#ROMNEY!WA#ROMNEY!WI#ROMNEY!WV#ROMNEY!WY#ROMNEY

!IA#SANTORUM!NH#ROMNEY!SC#GINGRICH!DC#DONEGAN 
